### ISSUE TITLE
Migrate to Typescript :)

### ISSUE THREAD

**Issue by CHR-onicles** [CHR-onicles/Whatsapp-bot#99]

**Comment by PiyushDuggal-source** [comment]
Hey, I am Piyush, I would like to help you convert this project into a Typescript based Project.

**Comment by CHR-onicles** [comment]
> Hey, I am Piyush, I would like to help you convert this project into a Typescript based Project.

Hi Piyush, how do you intend to run the project while migrating?

**Comment by PiyushDuggal-source** [comment]
There is no way to run the typescript files with javascript files as of now (if there is, please let me know). We have to start from scratch in order to replicate this project :)

**Comment by CHR-onicles** [comment]
> There is no way to run the typescript files with javascript files as of now (if there is, please let me know). We have to start from scratch in order to replicate this project :)

Yeah true, but I wanted to know how you will run the project, considering the environment variable for mongodb url and remote authentication for the bot to work.

My question is how will you run it locally to make sure everything works before sending a PR for instance?

**Comment by PiyushDuggal-source** [comment]
We will run it using LocalAuth strategy, we can use one of our number and verify it for both ends (yours and mine). LocalAuth strategy provides a .wwebjs_auth(will add it in .gitignore) folder, which will take care of authentication.

Currently I am also creating a WhatsApp bot (inspired by you, obviously!) for my IIT-M Course using ts.

**Comment by CHR-onicles** [comment]
> We will run it using LocalAuth strategy, we can use one of our number and verify it for both ends (yours and mine). LocalAuth strategy provides a .wwebjs_auth(will add it in .gitignore) folder, which will take care of authentication.

Sounds good!

> Currently I am also creating a WhatsApp bot (inspired by you, obviously!) for my IIT-M Course using ts.

That's great to hear Piyush 🥳

**Comment by PiyushDuggal-source** [comment]
Let me know when we start then!

**Comment by CHR-onicles** [comment]
> Let me know when we start then!

Sure thing!

**Comment by CHR-onicles** [comment]
@PiyushDuggal-source I've started migrating on [this branch](https://github.com/CHR-onicles/Whatsapp-bot/tree/99-migrate-to-typescript), can I contact you via email?

**Comment by PiyushDuggal-source** [comment]
Yes, we can communicate via Email. :)

**Comment by CHR-onicles** [comment]
> Yes, we can communicate via Email. 🙂

Great, I don't see your email on your profile, so kindly send me a mail or drop yours here if you're cool with that

**Comment by PiyushDuggal-source** [comment]
duggalpiyush0@gmail.com

**Comment by CHR-onicles** [comment]
Closed by #140
